### ISSUE TITLE
Pluggin not working

### ISSUE THREAD

**Issue by Kalibr8** [dinhhuy258/vim-database#2]
Hi. I like what this plugin is trying to accomplish. Could really improve my workflow.
However, whenever I run UpdateRemotePlugins I encounter the following error:

Encountered TypeError loading plugin at $HOME/.local/share/nvim/plugged/vim-database/rplugin/python3/database: 'type' object is not subscriptable
Traceback (most recent call last):
  File "$HOME/.local/lib/python3.8/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
TypeError: 'type' object is not subscriptable

Tried the error fixes in the README, it's still not working. Please help.

**Comment by dinhhuy258** [comment]
Hi, Sorry for my late response...

For your error, I can not reproduce it on my local machine. Could you try to upgrade your python 3 version to python 3.9 to see whether the error still occurs?
Or you can update your pynvim plugin on your machine.

**Comment by Kalibr8** [comment]
Seeing this months later... Thanks, upgrading the neovim python provider ( g:python3_host_prog ) to 3.9 resolved the issue. However, I suggest reflecting this requirement in the README. There it cites python 3.7 as a dependency, which clearly isn't the case.
